import { Playfair_Display, Inter } from "next/font/google";
import "normalize.css";
import { themeClass } from "../theme.css";
import { Box } from "~/widgets/box";

const headingFont = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-heading",
  display: "swap",
});

const bodyFont = Inter({
  subsets: ["latin"],
  variable: "--font-body",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout = ({ children }: RootLayoutProps) => (
  <html
    lang="en"
    className={`${bodyFont.variable} ${headingFont.variable} ${themeClass}`}
  >
    <Box as="body" color="body" backgroundColor="body" textStyle="base">
      {children}
    </Box>
  </html>
);

export default RootLayout;
